version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run : bundle install
  test:
    docker:
      - image: cimg/ruby:2.7-node
    environment:
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: test
          command: bundle exec rake validate lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
