version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run :
          name: prerequisites
          command: bundle install
      - run:
          name: test
          command: bundle exec rake validate lint
workflows:
  version: 2
  test:
    jobs:
      - test
